ARG torcs_img

FROM ${torcs_img}

RUN mkdir -p torcs/BUILD

WORKDIR /torcs/BUILD

COPY / .

WORKDIR /

COPY /entrypoint-runtime.sh /

RUN chmod +x /entrypoint-runtime.sh

ENTRYPOINT ["/entrypoint-runtime.sh"]
